language: python
python:
  - "3.5"
sudo: false
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
env:
  - KMC_VERSION=3.0.0
  - KMC_VERSION=2.3.0
install:
  - "source ./install_dependancies.sh"
before_script:
  - pip install codecov
script:
  - "coverage run -m unittest discover -s plasmidtron/tests/ -p '*_test.py'" 
after_success:
  - codecov